config/routes.rb
Rails.application.routes.draw do
  #resources :pet_histories
  #resources :pets
  #resources :clients
  resources :clients do
    resources :pets do
      resources :pet_histories
    end
  end
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets, dependent: :destroy
    accepts_nested_attributes_for :pets, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

    def to_s
        name
    end

    #Cantidad de mascotas que tiene
    def count_pet
        pets.count
    end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :client
  has_many :pet_histories, dependent: :destroy

  accepts_nested_attributes_for :pet_histories, allow_destroy: true, reject_if: proc { |attributes| attributes['weight'].blank? }

    def to_s
        name
    end

    def history_count
      pet_histories.count
    end
  
    def avg_weight
      pet_histories.average(:weight)
    end
    
    def avg_height
      pet_histories.average(:heigth)
    end
    
    def max_weight
      pet_histories.pluck(:weight).max
    end
    
    def max_height
      pet_histories.pluck(:heigth).max
    end
end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
  belongs_to :pet

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find params[:id]
  end

  # GET /clients/new
  def new
    @client = Client.new
    @client.pets.build
    # Esto crea una nueva instancia de Cliente y 1 instancia de Mascota que pertenecen al Cliente.
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find params[:id]
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    if @client.save
     redirect_to client_path(@client)
    else
     render ‘new’
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    @client = Client.find params[:id]
    respond_to do |format|
      if @client.update_attributes(client_params)
        format.html { redirect_to client_path(@client), notice: 'Cliente fue Actualizado correctamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find params[:id]
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Cliente fue Eliminado correctamente.' }
    end
  end

  private
    def client_params
      # Esto permite que los atributos de apartment sean guardados.
      # El parametró destroy  nos permite eliminar un apartment cuando se enviar el formulario.
      params.require(:client).permit(:name, :phone, :email, pets_attributes: [:id, :name, :race, :birthdate, :client_id, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  #before_action :set_pet_history, only: [:show, :edit, :update, :destroy]
  before_action :find_pet
  before_action :find_client
  # GET /pet_histories
  # GET /pet_histories.json
  def index
    @pet_histories = @pet.pet_histories# Se muestran los historiales asociados a este mascota
  end

  # GET /pet_histories/1
  # GET /pet_histories/1.json
  def show
    @pet_history = PetHistory.find(params[:id])
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
  end

  # GET /pet_histories/1/edit
  def edit
    @pet_history = PetHistory.find(params[:id])
  end

  # POST /pet_histories
  # POST /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)#Strong parameters, previene ataques de mass assignment
    @pet_history.pet = @pet #Asignamos la mascota, ya no es necesario pasarlo en el formulario, ahora viene en la url
    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to client_pet_pet_history_path(@client, @pet, @pet_history), notice: 'Se creo Consulta Correctamente.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /pet_histories/1
  # PATCH/PUT /pet_histories/1.json
  def update
    @pet_history = PetHistory.find params[:id]
    respond_to do |format|
      if @pet_history.update(pet_history_params.merge(pet: @pet))# Se añade la mascota que se obtuvo en la llamada a find_pet
        format.html { redirect_to client_pet_pet_histories_path(@client,@pet, @pet_history), notice: 'Consulta Editada Correctamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /pet_histories/1
  # DELETE /pet_histories/1.json
  def destroy
    @pet_history = PetHistory.find params[:id]
    @pet_history.destroy
    respond_to do |format|
      format.html { redirect_to client_pet_pet_histories_url, notice: 'Consulta eliminada correctamente.' }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def pet_history_params
      params.require(:pet_history).permit(:weight, :heigth, :description, :pet_id)
    end
  
    def find_pet
      @pet = Pet.find params[:pet_id]
    end

    def find_client
      @client = Client.find params[:client_id]
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  #before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :find_client

  # GET /pets
  # GET /pets.json
  def index
    @pets = @client.pets# Se muestran las macotas asociados a este cliente
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pet = Pet.find(params[:id])   
  end

  # GET /pets/new
  def new
    @pet = Pet.new    
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])   
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)#Strong parameters, previene ataques de mass assignment
    @pet.client = @client #Asignamos el cliente, ya no es necesario pasarlo en el formulario, ahora viene en la url
    respond_to do |format|
      if @pet.save
        format.html { redirect_to client_pet_path(@client, @pet), notice: 'Mascota fue Creada correctamente.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    @pet = Pet.find params[:id]
    respond_to do |format|
      if @pet.update(pet_params.merge(client: @client))# Se añade el client que se obtuvo en la llamada a find_client
        format.html { redirect_to client_pet_path(@client, @pet), notice: 'Macota Actualizada correctamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet = Pet.find params[:id]
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to client_pets_url, notice: 'Mascota Eliminada correctamente.' }
    end
  end

  private
    #def pet_params
    #  params.require(:pet).permit(:name, :race, :birthdate, :client_id)
    #end

    def pet_params
      params.require(:pet).permit(:name, :race, :birthdate, pet_histories_attributes: [:id, :weight, :heigth, :description, :pet_id, :_destroy])
    end

    def find_client
      @client = Client.find params[:client_id]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/edit.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
    <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">EDICION DE CLIENTE</h1>

    <%= render 'form', client: @client %>

    <div class="text-center pt-4">
        <%= link_to 'VER', @client, class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %> |
        <%= link_to 'VOLVER', clients_path, class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %>
    </div>
</div>

app/views/clients/index.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
 
  <% if notice.present? %>
    <div class="container mb-4 px-5 text-center">
      <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
        <strong>ATENCION!</strong> <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>

  <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">CLIENTES</h1>

  <table class="shadow-lg table mt-3">
    <thead class="thead-dark text-center">
      <tr>
        <th>N° de Mascotas</th>
        <th>NOMBRE</th>
        <th>TELEFONO</th>
        <th>CORREO</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="text-center">
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.count_pet %></td>
          <td><%= client.name %></td>
          <td><%= client.phone %></td>
          <td><%= client.email %></td>
          <td><%= link_to 'VER', client, class:"btn btn-primary rounded-pill btn-sm text-white font-weight-bold" %></td>
          <td><%= link_to 'EDITAR', edit_client_path(client), class:"btn btn-warning rounded-pill btn-sm text-white font-weight-bold" %></td>
          <td><%= link_to 'ELIMINAR', client, method: :delete, data: { confirm: 'Estas Segur@?' }, class:"btn btn-danger rounded-pill btn-sm text-white font-weight-bold" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Cliente', new_client_path, class:"btn btn-success btn-lg btn-block rounded-pill text-white mt-3 border border-info"  %>
</div>

app/views/clients/new.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
    <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">NUEVO CLIENTE</h1>

    <%= render 'form', client: @client %>
    
    <hr>
    <div class="text-center">
        <%= link_to 'VOLVER', clients_path, class:"btn btn-dark rounded-pill border border-white btn-sm text-center"%>
    </div>        
</div>

app/views/clients/show.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
    <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">DETALLE CLIENTE</h1>
    
    <% if notice.present? %>
      <div class="container mb-4 px-5 text-center">
        <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
          <strong>ATENCION!</strong> <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>

    <div class="text-center mt-3">
      <p>
      <strong>NOMBRE:</strong>
      <%= @client.name %>
      </p>

      <p>
        <strong>TELEFONO:</strong>
        <%= @client.phone %>
      </p>

      <p>
        <strong>CORREO:</strong>
        <%= @client.email %>
      </p>
     

      <td><%= link_to 'Ver Mascotas', client_pets_path(@client), class:"btn btn-primary rounded-pill border border-white btn-sm text-center" %></td>
    </div>
    <hr>
    <div>
      <h3 class="text-center" style="font-size:20px; text-shadow: 0.05em 0.1em 0.05em #333">MASCOTAS CLIENTE</h3>
    </div>
    <div>
      <table class="shadow-lg table mt-3">
        <thead class="thead-dark text-center">
          <tr>
            <th>NOMBRE</th>
            <th>PESO MAXIMO</th>
            <th>ALTURA MAXIMA</th>
          </tr>
        </thead>

        <tbody class="text-center">
          <% @client.pets.each do |pet|%>
            <tr>
              <td><%= pet.name %></td>
              <td><%= pet.max_weight %></td>
              <td><%= pet.max_height %></td>              
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
        
    <div class="text-center pt-4">
      <%= link_to 'EDITAR', edit_client_path(@client), class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %> |
      <%= link_to 'VOLVER', clients_path, class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %>
    </div>
    
</div>

app/views/home/index.html.erb
<div class="shadow-lg p-3 mb-5 bg-white rounded jumbotron">
  <h1 class="display-4">Hola, Bienvenido al Desafio: El Veterinario!</h1>
  <p class="lead">El desafio se logro hacer con 3 niveles de Anidados Cliente, Mascota y el Historial de Mascotas.</p>
  <hr class="my-4">
  <p>Comenzar desde Vista Clientes.</p>  
   <%= link_to "Clientes", clients_path, class:"btn btn-primary btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElVeterinario</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Fonts Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
    <!--Fonts Google-->
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    <!--Hoja de Estilos-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--JavaScrip-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Librerias Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body>
           
    <div class="wrapper">
      <!-- Sidebar Holder -->
      <nav id="sidebar">
        <div class="text-center mr-1 pr-1">
          <%= image_tag 'https://1.bp.blogspot.com/-yOWhBekuZHM/UJNKlZG85QI/AAAAAAAAiw4/--s4NQgNAH4/s1600/gatos+y+perros+png+(10).png', class:"img-fluid"%>
        </div>
        <div class="sidebar-header">
          <h3>Desafio:<br>El veterinario </h3>
          </h3>
        </div>

        <ul class="list-unstyled components">
          <p>Menu General</p>
          <li>
            <%= link_to 'HOME', root_path %>
          </li>
          <li>            
            <%= link_to 'CLIENTES', clients_path %>
          </li>

        </ul>

      </nav>

      <!-- Page Content Holder -->
      <div id="content">                
          <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn mb-3">
                                  <i class="glyphicon glyphicon-align-left"></i>
                                  <span><i class="fas fa-eye"></i> PANEL</span>
          </button>
          <%= yield %>
      </div>
    </div>
    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Bootstrap Js CDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script type="text/javascript">
      $(document).ready(function() {


        $('#sidebarCollapse').on('click', function() {
          $('#sidebar, #content').toggleClass('active');
          $('.collapse.in').toggleClass('in');
          $('a[aria-expanded=true]').attr('aria-expanded', 'false');
        });
      });
    </script>
  </body>
</html>

app/views/pet_histories/index.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
 
  <% if notice.present? %>
    <div class="container mb-4 px-5 text-center">
      <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
        <strong>ATENCION!</strong> <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>

  <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">CONSULTAS DE <%= @pet.name.upcase%></h1>

  <table class="shadow-lg table mt-3">
    <thead class="thead-dark text-center">
      <tr>
        <th>PESO</th>
        <th>ALTURA</th>
        <th>DESCRIPCION</th>        
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="text-center">
        <% @pet_histories.each do |pet_history| %>
        <tr>
          <td><%= pet_history.weight %></td>
          <td><%= pet_history.heigth %></td>
          <td><%= pet_history.description %></td>          
          <td><%= link_to 'VER', client_pet_pet_history_path(@client, @pet, pet_history), class:"btn btn-primary rounded-pill btn-sm text-white font-weight-bold" %></td>
          <td><%= link_to 'EDITAR', edit_client_pet_pet_history_path(@client, @pet, pet_history), class:"btn btn-warning rounded-pill btn-sm text-white font-weight-bold" %></td>
          <td><%= link_to 'ELIMINAR', client_pet_pet_history_url(@client, @pet, pet_history), method: :delete, data: { confirm: 'Estas segur@?' }, class:"btn btn-danger rounded-pill btn-sm text-white font-weight-bold" %></td>        
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nueva Consulta', new_client_pet_pet_history_path, class:"btn btn-success btn-lg btn-block rounded-pill text-white mt-3 border border-info"  %>
  <hr>
  <div class="text-center">
    <%= link_to 'VOLVER', client_pet_path(@client, @pet), class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %>
  </div>
</div>

app/views/pet_histories/show.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
    <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">DETALLE CONSULTA DE "<%= @pet.name.upcase%>"</h1>
    
    <% if notice.present? %>
      <div class="container mb-4 px-5 text-center">
        <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
          <strong>ATENCION!</strong> <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>

    <div class="text-center mt-3">
      <p>
        <strong>PESO:</strong>
        <%= @pet_history.weight %>
      </p>

      <p>
        <strong>ALTURA:</strong>
        <%= @pet_history.heigth %>
      </p>

      <p>
        <strong>DESCRIPCION:</strong>
        <%= @pet_history.description %>
      </p>

      <p>
        <strong>MASCOTA:</strong>
        <%= @pet_history.pet %>
      </p>

    </div>
    <hr>     
    <div class="text-center pt-4">
      <%= link_to 'EDITAR', edit_client_pet_pet_history_path(@client, @pet, @pet_history), class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %> |
      <%= link_to 'VOLVER', client_pet_pet_histories_path, class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %>
    </div>
    
</div>

app/views/pets/index.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
 
  <% if notice.present? %>
    <div class="container mb-4 px-5 text-center">
      <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
        <strong>ATENCION!</strong> <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>

  <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">MASCOTAS DE <%= @client.name.upcase%></h1>

  <table class="shadow-lg table mt-3">
    <thead class="thead-dark text-center">
      <tr>
        <th>NOMBRE</th>
        <th>RAZA</th>
        <th>FECHA NACIMIENTO</th>
        <th>VISITAS</th>
        <th>HISTORIAL</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="text-center">
        <% @pets.each do |pet| %>
        <tr>
          <td><%= pet.name %></td>
          <td><%= pet.race %></td>
          <td><%= pet.birthdate %></td>
          <td><%= pet.history_count %></td>
          <td>
              <% pet.pet_histories.each do |pet_history| %>
                <span><%= pet_history.description %></span> => <span><%= pet_history.created_at %></span><hr>
              <% end %>
          </td>
          <td><%= link_to 'VER', client_pet_path(@client, pet), class:"btn btn-primary rounded-pill btn-sm text-white font-weight-bold" %></td>
          <td><%= link_to 'EDITAR', edit_client_pet_path(@client, pet), class:"btn btn-warning rounded-pill btn-sm text-white font-weight-bold" %></td>
          <td><%= link_to 'ELIMINAR', client_pet_url(@client, pet), method: :delete, data: { confirm: 'Estas segur@?' }, class:"btn btn-danger rounded-pill btn-sm text-white font-weight-bold" %></td>        
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nueva Mascota', new_client_pet_path, class:"btn btn-success btn-lg btn-block rounded-pill text-white mt-3 border border-info"  %>
  <hr>
  <div class="text-center">
    <%= link_to 'VOLVER', client_path(@client), class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
    <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">NUEVA MASCOTA</h1>

    <%= render 'form', pet: @pet %>
    
    <hr>
    <div class="text-center">
        <%= link_to 'VOLVER', client_pets_path, class:"btn btn-dark rounded-pill border border-white btn-sm text-center"%>
    </div>        
</div>

app/views/pets/show.html.erb
<div class="shadow-lg p-4 mb-5 bg-white rounded">
    <h1 class="text-center" style="font-size:40px; text-shadow: 0.05em 0.1em 0.05em #333">DETALLE MASCOTA "<%= @pet.name.upcase%>"</h1>
    
    <% if notice.present? %>
      <div class="container mb-4 px-5 text-center">
        <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
          <strong>ATENCION!</strong> <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>

    <div class="text-center mt-3">
      <p>
        <strong>NOMBRE:</strong>
        <%= @pet.name %>
      </p>

      <p>
        <strong>RAZA:</strong>
        <%= @pet.race %>
      </p>

      <p>
        <strong>FECHA DE NACIMIENTO:</strong>
        <%= @pet.birthdate %>
      </p>

      <p>
        <strong>CLIENTE:</strong>
        <%= @pet.client %>
      </p>
     

      <td><%= link_to 'Ver Historial', client_pet_pet_histories_path(@client, @pet), class:"btn btn-primary rounded-pill border border-white btn-sm text-center" %></td>
    </div>
    <hr>     
    <div>
      <h3 class="text-center" style="font-size:20px; text-shadow: 0.05em 0.1em 0.05em #333">ESTADISTICAS MASCOTA</h3>
    </div>
    <div>
      <table class="shadow-lg table mt-3">
        <thead class="thead-dark text-center">
          <tr>
            <th>Peso Promedio</th>
            <th>Altura Promedio</th>
            <th>La altura Maxima</th>
            <th>El peso maximo</th>
          </tr>
        </thead>

        <tbody class="text-center">
          <tr>
            <td><%= @pet.avg_weight %></td>
            <td><%= @pet.avg_height %></td>
            <td><%= @pet.max_height %></td>
            <td><%= @pet.max_weight %></td>
          </tr>   
        </tbody>
      </table>
    </div>
    
    <div class="mt-5">
      <h3 class="text-center" style="font-size:20px; text-shadow: 0.05em 0.1em 0.05em #333">RESUMEN HISTORIAL</h3>
    </div>
    <div>
      <table class="shadow-lg table mt-3">
        <thead class="thead-dark text-center">
          <tr>
            <th>Altura</th>
            <th>Peso</th>
            <th>Descripcion</th>
            <th>Fecha</th>
          </tr>
        </thead>

        <tbody class="text-center">
          <% @pet.pet_histories.each do |pet_history| %>
          <tr>
            <td><%= pet_history.heigth %></td>
            <td><%= pet_history.weight %></td>
            <td><%= pet_history.description %></td>
            <td><%= pet_history.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
        
    <div class="text-center pt-4">
      <%= link_to 'EDITAR', edit_client_pet_path(@client, @pet), class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %> |
      <%= link_to 'VOLVER', client_pets_path, class:"btn btn-dark rounded-pill border border-white btn-sm text-center" %>
    </div>
    
</div>